const menu=document.querySelector('.menu'),mobile=document.querySelector('#mobileNav');
menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';menu.setAttribute('aria-expanded',String(!open));mobile.hidden=open;document.body.style.overflow=open?'hidden':'';menu.setAttribute('aria-label',open?'Open menu':'Close menu')});
mobile?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{mobile.hidden=true;menu.setAttribute('aria-expanded','false');document.body.style.overflow=''}));
const isHome=/\/(index\.html)?$/.test(location.pathname);if(isHome){document.querySelectorAll('.nav a,.mobile-nav a').forEach(a=>{if(a.textContent.trim()==='Collection')a.href='collection.html';if(a.textContent.trim()==='Enquire')a.href='connect.html'});document.querySelector('.discover')?.setAttribute('href','collection.html');document.querySelectorAll('.line-link').forEach(a=>{if(a.textContent.includes('Commission'))a.href='connect.html'})}
const luxuryImages=['https://images.pexels.com/photos/32862205/pexels-photo-32862205.jpeg?auto=compress&cs=tinysrgb&w=1800','https://images.unsplash.com/photo-1641996250159-9d2bbfb483fa?auto=format&fit=crop&fm=jpg&q=80&w=2200','https://images.pexels.com/photos/16148393/pexels-photo-16148393.jpeg?auto=compress&cs=tinysrgb&w=1800','https://images.pexels.com/photos/30219469/pexels-photo-30219469.jpeg?auto=compress&cs=tinysrgb&w=2200'];
document.querySelectorAll('.piece-art').forEach((btn,i)=>{if(luxuryImages[i]){btn.dataset.image=luxuryImages[i];const img=btn.querySelector('.photo');if(img)img.src=luxuryImages[i]}});
const viewer=document.querySelector('#viewer'),viewerName=document.querySelector('#viewerName'),viewerArt=document.querySelector('.viewer-art');
document.querySelectorAll('.piece-art').forEach(btn=>btn.addEventListener('click',()=>{if(!viewer)return;viewer.hidden=false;viewerName.textContent=btn.dataset.name;const image=btn.dataset.image;if(image){viewerArt.innerHTML=`<img src="${image}" alt="${btn.dataset.name}">`;viewerArt.style.cssText='width:min(900px,90vw);height:min(78vh,900px);background:#111;display:grid;place-items:center;overflow:hidden';viewerArt.querySelector('img').style.cssText='width:100%;height:100%;object-fit:contain'}document.body.style.overflow='hidden'}));
function closeViewer(){if(!viewer)return;viewer.hidden=true;document.body.style.overflow='';if(viewerArt)viewerArt.innerHTML=''}
document.querySelector('.viewer-close')?.addEventListener('click',closeViewer);viewer?.addEventListener('click',e=>{if(e.target===viewer)closeViewer()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(viewer&&!viewer.hidden)closeViewer();if(mobile&&!mobile.hidden){mobile.hidden=true;menu?.setAttribute('aria-expanded','false');document.body.style.overflow=''}}});
const form=document.querySelector('#contactForm'),status=document.querySelector('#status');form?.addEventListener('submit',e=>{e.preventDefault();if(!form.checkValidity()){status.textContent='Please complete your name, email and message.';form.reportValidity();return}status.textContent='Thank you — your enquiry is ready to be sent.';form.reset()});
const io=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.style.opacity='1';x.target.style.transform='none';io.unobserve(x.target)}}),{threshold:.12});document.querySelectorAll('.piece,.story-copy,.story-image,.steps>div,.statement-grid,.section-head,.contact>div,.contact form,.detail,.detail-copy,.detail-image').forEach(x=>{x.style.opacity='0';x.style.transform='translateY(24px)';x.style.transition='opacity .9s ease,transform .9s ease';io.observe(x)});
(function luxuryCursor(){if(matchMedia('(pointer:coarse)').matches)return;let dot=document.querySelector('.cursor-dot'),ring=document.querySelector('.cursor-ring');if(!dot){dot=document.createElement('div');dot.className='cursor-dot';document.body.appendChild(dot)}if(!ring){ring=document.createElement('div');ring.className='cursor-ring';document.body.appendChild(ring)}Object.assign(dot.style,{position:'fixed',width:'7px',height:'7px',borderRadius:'50%',background:'#f3eee5',boxShadow:'0 0 0 1px rgba(198,173,122,.85)',pointerEvents:'none',zIndex:'99999',left:'0',top:'0',transform:'translate(-50%,-50%)'});Object.assign(ring.style,{position:'fixed',width:'32px',height:'32px',border:'1px solid #c6ad7a',borderRadius:'50%',pointerEvents:'none',zIndex:'99998',left:'0',top:'0',transform:'translate(-50%,-50%)',transition:'width .3s cubic-bezier(.16,1,.3,1),height .3s cubic-bezier(.16,1,.3,1),background .3s'});let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;addEventListener('pointermove',e=>{x=e.clientX;y=e.clientY;dot.style.left=x+'px';dot.style.top=y+'px'});(function move(){rx+=(x-rx)*.2;ry+=(y-ry)*.2;ring.style.left=rx+'px';ring.style.top=ry+'px';requestAnimationFrame(move)})();document.addEventListener('pointerover',e=>{if(e.target.closest('a,button,input,select,textarea')){ring.style.width='58px';ring.style.height='58px';ring.style.background='rgba(198,173,122,.08)'}});document.addEventListener('pointerout',e=>{if(!e.relatedTarget?.closest?.('a,button,input,select,textarea')){ring.style.width='32px';ring.style.height='32px';ring.style.background='transparent'}})})();
